server:
  port: 8080

spring:
  redis:
    database: 1
    host: localhost
    port: 6379
    lettuce:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 5000

lock4j:
  enable-lock-for-controller: true
